### ISSUE TITLE
Doesn't support arm64

### ISSUE THREAD

**Issue by ralongit** [RaoulDuke-Esq/Beats-Pi#2]
I have a raspberry pi 4 device with 4gb ram and when I do apt-get update, I get the following error:

N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'https://raw.githubusercontent.com/RaoulDuke-Esq/Beats-Pi/master buster InRelease' doesn't support architecture 'arm64'

**Comment by RaoulDuke-Esq** [comment]
Interesting- I'm using a 4GB Pi4  and do not get that.  Could you please provide the output of the following commands:

cat /etc/debian_version

cat /etc/os-release

uname -a

dpkg --print-architecture

**Comment by ralongit** [comment]
cat /etc/debian_version
output:
```
buster/sid
```

cat /etc/os-release
output:
```
NAME="Ubuntu"
VERSION="19.10 (Eoan Ermine)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 19.10"
VERSION_ID="19.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
```
uname -a
output:
`Linux krpi4 5.3.0-1019-raspi2 #21-Ubuntu SMP Mon Feb 17 14:05:03 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux`

dpkg --print-architecture
output:
`arm64`

**Comment by RaoulDuke-Esq** [comment]
Thanks for that- makes the issue very clear.  This repo contains Beats compiled for Raspbian Buster.  

It is possible that this repo will work for you if you do:
`sudo dpkg --add-architecture armhf`

If that doesn't work, let me know and I'll see about adding an arm64 version in the near future.

**Comment by ralongit** [comment]
It did install it but it doesn't let me run Metricbeat.
starting the service with systemctl doesn't do much and running the script provides the following output(same result if I run as sudo): 

```
ubuntu@krpi4:/$ cd /usr/share/metricbeat/bin
ubuntu@krpi4:/usr/share/metricbeat/bin$ ls
metricbeat
ubuntu@krpi4:/usr/share/metricbeat/bin$ ./metricbeat
-bash: ./metricbeat: No such file or directory
```

**Comment by RaoulDuke-Esq** [comment]
That's helpful- thanks.  I'll let you know when I have an updated repo ready for you to test.

**Comment by RaoulDuke-Esq** [comment]
So...  This is ready for you to test.  arm64 packages are created and posted.  Give it a whirl and let me know how it goes!

You may want to first
`sudo dpkg --remove-architecture armhf`

**Comment by ralongit** [comment]
Different error:

`-bash: ./metricbeat: cannot execute binary file: Exec format error
`
![image](https://user-images.githubusercontent.com/39119258/77840962-7d088e80-7195-11ea-9b4e-9e620e90945b.png)

**Comment by ralongit** [comment]
When running in sudo:
```

ubuntu@krpi4:/usr/share/metricbeat/bin$ sudo ./metricbeat
./metricbeat: 2: Syntax error: end of file unexpected (expecting ")")
```

**Comment by RaoulDuke-Esq** [comment]
I think we're good to go now.  I made an extra SD with the OS you're using on it and was able to install and run Metricbeat with systemd.  Please remove the packages currently installed, update apt, then reinstall.

`sudo systemctl start metricbeat.service`
does not give you any feedback.
`systemctl status metricbeat`
will give you some information though, as will 
`journalctl -u metricbeat`

Assuming your metricbeat.yml has the proper output configured, you should start getting metrics.

**Comment by ralongit** [comment]
Thanks for all of your efforts, it works!
