### ISSUE TITLE
Missing iptables module

### ISSUE THREAD

**Issue by miszterx** [RaoulDuke-Esq/Beats-Pi#3]
Hi,

I just tried your compiled packages. Works fine! However I released the iptables module is missing. I copied it from another system and it works fine. Can you add iptables module as well for the next package?

Thanks!

**Comment by RaoulDuke-Esq** [comment]
Thanks for the heads up!  

FYI- haven't been able successfully compile for 7.6.2. so I'll likely be trying to work this into 7.6.3.

**Comment by miszterx** [comment]
Perfect! Thanks! Looking forward to try it.

**Comment by RaoulDuke-Esq** [comment]
Got 7.6.2 working with the rest of the modules including ipables!
