### ISSUE TITLE
How do I install older versions of beats?

### ISSUE THREAD

**Issue by klausagnoletti** [RaoulDuke-Esq/Beats-Pi#4]
Hi

I would want to install filebeat 7.6.2 rather than 7.7 to my pi. What is the easy way to do that? Are archived releases available for me to download manually, for instance? Or can I use apt pinning to point to other releases? Didn't seem that other versions than 7.7 are available in the repo right now.

Thanks

/klaus

**Comment by RaoulDuke-Esq** [comment]
That's a great question.  I had to refactor a bunch of the behind the scenes code for this, which resulted in me having to nuke the repo a few times.  I'm hoping that in future, older versions will remain available.  However, I'm also going to post the .deb files for each release from now on just in case and to help folks doing offline installs.

There's now an "Old-DEBs" folder.  This is probably the easiest way to get you what you need.

Enjoy!

**Comment by klausagnoletti** [comment]
cool! thanks!
